### PR TITLE
Implement setField for checkbox.

### PR DESCRIPTION
**Pull request by njam**
Click on checkbox is not reliable. We need a method that will allow us not just toggle checkbox but set the exact value we want.
@njam ?

### CODE REVIEW

**Comment by njam** [comment]
@vogdb please have a look

**Comment by vogdb** [comment]
looks ok. Wdyt think about having a method `getValue` or smth? This looks not nice: `$this->_navigator->executeJs('return document.getElementById("id-select").value')`

**Comment by njam** [comment]
Good point!

I added `getAttribute()` which I think might be sufficient, so we don't need to add getters for all the different attributes.
It still might be useful to have a `getField()` - but implementing that is quite complicated and some uncertainties need to be answered (like how a radiogroup's value should be represented - array?). I'd not do it now.
wdyt?

**Comment by vogdb** [comment]
Interesting about `$this->getAttribute($locator, 'innerHTML');`. If it works fine then lgtm.

**Comment by njam** [comment]
Ups I committed to the wrong branch, wanna review last commit too - it's a small change?

**Comment by vogdb** [comment]
Very good. lgtm.

**Pull request merged**
